[package]
name = "bin"
version = "0.1.0"
authors = ["Scotow <contact@scotow.com>"]
edition = "2018"

[dependencies]
lib = { path = "../lib" }
nustify = { git = "https://github.com/scotow/nustify", rev = "ac011cc" }
uuid = { version = "0.8", features = ["serde"] }
num-format = "0.4"
async-io = "1.3"
futures-lite = "1.11"
structopt = "0.3"

[dev-dependencies]
uuid = { version = "0.8", features = ["v3"] }