name: CI

on:
  push:
    branches:
      - main
      - master
    tags:
      - "*.*.*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
  docker:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
    - name: Build and push Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: scotow/skysold/skysold
        tag_with_ref: true
        tag_with_sha: true
        push: true
